### ISSUE TITLE
Document MoonPhase.cpp

### ISSUE THREAD

**Issue by marcelstoer** [CelliesProjects/moonPhase#1]
I have no reason to doubt the correctness of `MoonPhase.cpp`. However, if you're not intimately familiar with the scientific foundation of the formulas you have no way of verifying the correctness. Two things would help greatly:

- those single-char variables should be renamed to something more expressive
- document the constants, ideally with references

**Comment by CelliesProjects** [comment]
Hi, thanks for your feedback. You do have some valid points.

You would be wise to doubt the correctness of `MoonPhase.cpp` because it is a copy-paste job from 'something-I-found-online'. 
My math skills are too limited to come up with a home made solution, I needed (wanted) a moon phase approximation for my aquarium led controller and found this code that I could use.
If your math skills are any good and you have a clue about what is going on in the code, feel free to edit and document the code and make a PR, I would appreciate it.
I will try to contact the original author and see if he is willing and able to provide some context and documentation, as I agree with your issue.

Now I have to find out why I didn't get a mail notifying me there was an issue, just stumbled on your issue, so that is why it took some time to reply.

**Comment by marcelstoer** [comment]
Never mind, if I _did_ have the necessary scientific understanding - or the time & motivation to learn - I didn't need the documentation 😉
